import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { createWizardServer } from '../v2/serve.mjs';
import { createSession, answerQuestion } from '../v2/interview.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const server=createWizardServer();
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const output=path.join(root,'output/playwright/byok');fs.mkdirSync(output,{recursive:true});
  const errors=[],calls=[],cspWarnings=[];
  page.on('console',message=>{if(message.text().includes('source')&&message.text().includes('Content Security'))cspWarnings.push(message.text());});
  page.on('pageerror',error=>errors.push(error.message));
  let response={reply:'<img src=x onerror="alert(1)"> Tell me what name you prefer.',proposal:'Alex'};
  let status=200, release=null, hold=false;
  await page.route('https://openrouter.ai/api/v1/chat/completions',async route=>{
    calls.push({body:route.request().postDataJSON(),headers:route.request().headers()});
    if(hold)await new Promise(resolve=>{release=resolve;});
    try{await route.fulfill({status,contentType:'application/json',body:JSON.stringify(status===200?{choices:[{message:{content:JSON.stringify(response)}}]}:{error:'Never display provider body'})});}catch{/* A cancelled request may already have closed. */}
  });
  await page.goto(origin);
  const seeded=answerQuestion(createSession(),'mission.purpose','PRIVATE_OTHER_ANSWER');
  await page.evaluate(value=>localStorage.setItem('hermes-soulmate-v2',JSON.stringify(value)),seeded);
  await page.reload();
  await page.locator('#ai-start').click();
  await page.screenshot({path:path.join(output,'connection-desktop.png'),fullPage:true,animations:'disabled'});
  await page.locator('#ai-model').fill('explicit/test-model');
  await page.locator('#ai-key').fill('synthetic-key-not-real-123');
  await page.locator('#ai-connect').click();
  assert.ok((await page.locator('#ai-error').innerText()).includes('agree'));
  assert.equal(calls.length,0);
  await page.locator('#ai-consent').check();
  await page.locator('#ai-model').fill('explicit/other-model');
  assert.equal(await page.locator('#ai-consent').isChecked(),false,'Changing model requires fresh consent');
  await page.locator('#ai-consent').check();
  await page.locator('#ai-connect').click();
  assert.equal(calls.length,0,'Connect does not call provider');
  await page.locator('#ai-message').fill('CHAT_ONLY_SENTINEL. Call me Alex.');
  await page.locator('#ai-send').click();
  await page.locator('#ai-accept').waitFor();
  assert.equal(calls.length,1);
  const sent=JSON.stringify(calls[0].body);
  assert.ok(sent.includes('What should Hermes call you?'));
  assert.ok(!sent.includes('PRIVATE_OTHER_ANSWER'));
  assert.ok(!sent.includes('synthetic-key-not-real-123'));
  assert.equal(await page.locator('.ai-messages img').count(),0,'Provider text is not executable markup');
  assert.ok((await page.locator('.ai-messages').innerText()).includes('<img'));
  await page.screenshot({path:path.join(output,'mock-proposal-desktop.png'),fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'mock-proposal-mobile.png'),fullPage:true,animations:'disabled'});
  await page.setViewportSize({width:1440,height:1000});
  let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('hermes-soulmate-v2')));
  assert.equal(stored.answers['identity.name'],undefined,'Suggestion cannot save itself');
  await page.locator('#ai-accept').click();
  assert.ok((await page.locator('#ai-current').innerText()).includes('most useful job'));
  assert.equal(await page.locator('.ai-message').count(),0,'Next question starts with empty chat');
  stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('hermes-soulmate-v2')));
  assert.equal(stored.answers['identity.name'],'Alex');
  assert.ok(!JSON.stringify(stored).includes('CHAT_ONLY_SENTINEL'));
  assert.ok(!JSON.stringify(stored).includes('synthetic-key-not-real-123'));

  await page.locator('#ai-close').click();
  await page.locator('[data-chapter="Models & providers"]').click();
  await page.locator('#ai-question').click();
  response={reply:'Here is a suggestion.',proposal:['Not decided','OpenAI']};
  await page.locator('#ai-message').fill('I am undecided.');
  await page.locator('#ai-send').click();
  await page.waitForFunction(()=>document.querySelector('#ai-error')?.textContent.length>0);
  assert.equal(await page.locator('#ai-accept').count(),0,'Invalid proposal cannot be accepted');
  stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('hermes-soulmate-v2')));
  assert.equal(stored.answers['models.provider'],undefined);

  status=401;
  await page.locator('#ai-message').fill('Try again.');await page.locator('#ai-send').click();
  await page.waitForFunction(()=>document.querySelector('#ai-error')?.textContent.length>0&&!document.querySelector('#ai-send')?.disabled);
  assert.ok(!(await page.locator('#ai-error').innerText()).includes('Never display'));
  assert.equal(await page.locator('#ai-message').inputValue(),'Try again.','Failed messages remain available for manual retry');
  status=200;hold=true;response={reply:'Late response',proposal:['OpenAI']};
  await page.locator('#ai-message').fill('Wait for this response.');await page.locator('#ai-send').click();
  await page.waitForFunction(()=>document.querySelector('#ai-send')?.disabled);
  while(!release)await new Promise(resolve=>setTimeout(resolve,10));
  await page.locator('#ai-close').click();
  await page.locator('[data-chapter="Memory & knowledge services"]').click();
  release();hold=false;
  await page.locator('#ai-question').click();
  assert.equal(await page.locator('#ai-accept').count(),0);
  assert.ok(!(await page.locator('.ai-messages').innerText()).includes('Late response'));
  await page.locator('#ai-disconnect').click();
  assert.equal(await page.locator('#ai-key').inputValue(),'');
  assert.equal(await page.locator('#ai-model').inputValue(),'');
  assert.equal(await page.locator('#ai-consent').isChecked(),false);
  await page.locator('#ai-close').click();await page.locator('#mobile-review').click();
  const downloadEvent=page.waitForEvent('download');await page.locator('#export').click();
  const exported=fs.readFileSync(await(await downloadEvent).path(),'utf8');
  assert.ok(!exported.includes('synthetic-key-not-real-123')&&!exported.includes('CHAT_ONLY_SENTINEL'));
  await page.reload();await page.locator('#ai-start').click();
  assert.equal(await page.locator('#ai-key').inputValue(),'');
  await page.setViewportSize({width:390,height:844});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:path.join(output,'ai-connect-mobile.png'),fullPage:true,animations:'disabled'});
  assert.deepEqual(errors,[]);
  assert.deepEqual(cspWarnings,[],'CSP must contain only valid browser source expressions');
  console.log('PASS AI browser: consent, current-question privacy, discussion/accept/advance, invalid proposals, XSS, error handling, cancellation race, ephemeral keys/chat and exports');
} finally {await browser.close();await new Promise(resolve=>server.close(resolve));}
